wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers:
  value: 3
layer_size:
  value: 32
learning_rate:
  value: 0.0001
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: xavier
