wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
hidden_layers:
  value: 4
layer_size:
  value: 128
learning_rate:
  value: 0.001
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: random
