wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers:
  value: 4
layer_size:
  value: 64
learning_rate:
  value: 0.001
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
