wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers:
  value: 5
layer_size:
  value: 128
learning_rate:
  value: 0.001
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: xavier
